export function dataProcessor(data) {
    return data.sort((a, b) => a.id - b.id).map(item => ({
        id: item["id"],
        publisher_name: item["Publisher Name"],
        component_name: item["Component Name"],
        component_version: item["Component Version"],
        component_detailed_version: item["Component Detailed Version"],
        end_of_support: item["End of Support"],
        component_creation: item["Component Creation"],
        component_modification: item["Component Modification"],
        component_definition_source: item["Component Definition Source"],
        instance_tags: item["Instance Tags"],
        component_tags: item["Component Tags"],
        suppressed: item["Suppressed"],
        shared: item["Shared"],
        always_not_charged: item["Always Not Charged"],
        product_name: item["Product Name"],
        product_version: item["Product Version"],
        product_metric: item["Product Metric"],
        cloud_pak_or_flexpoint_bundle: item["Cloud Pak or FlexPoint Bundle"],
        entitled: item["Entitled"],
        charged: item["Charged"],
        bundling_option_from_ibm_catalog: item["Bundling Option from IBM Catalog"],
        one_to_one: item["One to One"],
        confirmed: item["Confirmed"],
        excluded: item["Excluded"],
        comment: item["Comment"],
        bundling_tag_used: item["Bundling Tag Used"],
        imported_part_numbers: item["Imported Part Numbers"],
        computer_name: item["Computer Name"],
        data_source_name: item["Data Source Name"],
        computer_first_seen: item["Computer First Seen"],
        computer_last_seen: item["Computer Last Seen"],
        computer_deletion_date: item["Computer Deletion Date"],
        operating_system: item["Operating System"],
        dns_name: item["DNS Name"],
        ip_address: item["IP Address"],
        internal_computer_id: item["Internal Computer ID"],
        data_source_computer_id: item["Data Source Computer ID"],
        status: item["Status"],
        computer_type: item["Computer Type"],
        partition_cores: item["Partition Cores"],
        server_id: item["Server ID"],
        server_serial_number: item["Server Serial Number"],
        server_vendor: item["Server Vendor"],
        server_model: item["Server Model"],
        server_type: item["Server Type"],
        server_cores: item["Server Cores"],
        processor_brand_string: item["Processor Brand String"],
        vendor_brand_type_model: item["Vendor Brand Type Model"],
        system_model: item["System Model"],
        pvu_per_core: item["PVU per Core"],
        changed_pvu_value: item["Changed PVU Value"],
        default_pvu_value: item["Default PVU Value"],
        lpar_entitlement: item["LPAR Entitlement"],
        is_capped: item["Is Capped"],
        shared_mode: item["Shared Mode"],
        partition_virtual_processors: item["Partition Virtual Processors"],
        server_active_sockets: item["Server Active Sockets"],
        virtual_shared_pool_cores: item["Virtual Shared Pool Cores"],
        physical_shared_pool_cores: item["Physical Shared Pool Cores"],
        cluster_name: item["Cluster Name"],
        cluster_cores: item["Cluster Cores"],
        shared_pool_id: item["Shared Pool ID"],
        logical_processors: item["Logical Processors"],
        delayed_data_upload: item["Delayed Data Upload"],
        missing_software_scan: item["Missing Software Scan"],
        outdated_capacity_scan: item["Outdated Capacity Scan"],
        old_scanner_version: item["Old Scanner Version"],
        outdated_bigfix_agent_version: item["Outdated BigFix Agent Version"],
        has_low_disk_space: item["Has Low Disk Space"],
        is_out_of_sync: item["Is Out of Sync"],
        has_missing_prerequisites: item["Has Missing Prerequisites"],
        agent_version: item["Agent Version"],
        scanner_version: item["Scanner Version"],
        catalog_scan_successful: item["Catalog Scan Successful"],
        software_tags_scan_successful: item["Software Tags Scan Successful"],
        catalog_version: item["Catalog Version"],
        last_scan_attempt: item["Last Scan Attempt"],
        scanning_shared_disks: item["Scanning Shared Disks"],
        mounted_shared_disks: item["Mounted Shared Disks"],
        catalog_scan_not_uploaded: item["Catalog Scan Not Uploaded"],
        last_successful_capacity_scan: item["Last Successful Capacity Scan"],
        from_software_template: item["From Software Template"],
        installation_path: item["Installation Path"],
        discovery_start: item["Discovery Start"],
        discovery_end: item["Discovery End"],
        present: item["Present"],
        details: item["Details"],
    }));
}
